# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: reader-app-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: reader-app
  replicas: 1
  template:
    metadata:
      name: reader-app-tmpl
      labels:
        app: reader-app
    spec:
      containers:
        - name: reader-app
          image: reader-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 11000
          volumeMounts: 
            - mountPath: /db/data
              name: data-mount
        
      volumes: 
        - name: data-mount
          hostPath: 
            path: /db/   
            type: DirectoryOrCreate