# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: calc-app-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: calc-app
  replicas: 1
  template:
    metadata:
      name: calc-app-tmpl
      labels:
        app: calc-app
    spec:
      containers:
        - name: calc-app
          image: calc-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
            - containerPort: 10000