# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: analyzer-app-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: analyzer-app
  replicas: 1
  template:
    metadata:
      name: analyzer-app-tmpl
      labels:
        app: analyzer-app
    spec:
      containers:
        - name: analyzer-app
          image: analyzer-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000
            - containerPort: 10000