# deployment.yaml

apiVersion: apps/v1
kind: Deployment
metadata:
  name: alarm-app-deploy
  labels:
    type: restapi
spec:
  selector: 
    matchLabels:
      app: alarm-app
  replicas: 1
  template:
    metadata:
      name: alarm-app-tmpl
      labels:
        app: alarm-app
    spec:
      containers:
        - name: alarm-app
          image: alarm-app:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 9000